apiVersion: v2
name: pocketbase
description: Helm chart for the Clan Europe PocketBase backend
type: application
version: 0.1.21
appVersion: "v0.11.0"
dependencies:
  - name: common
    version: "0.1.10"
    repository: "file://../common"
