apiVersion: v2
name: cvc
description: Helm chart for the Clan Europe CVC legacy Python Discord bot
type: application
version: 0.1.9
appVersion: "latest"
dependencies:
  - name: common
    version: "0.1.9"
    repository: "file://../common"
