{{- $c := .Values.credentials | default dict -}}
{{- if and (not $c.existingSecret) (or $c.serviceAccountJson $c.configJson) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $c.secretName | default "cvc-credentials" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with $c.serviceAccountJson }}
  service_account.json: {{ . | quote }}
  {{- end }}
  {{- with $c.configJson }}
  config.json: {{ . | quote }}
  {{- end }}
{{- end }}
