apiVersion: v2
name: event
description: Helm chart for the Clan Europe event management Discord bot
type: application
version: 0.1.16
appVersion: "v0.7.0"
dependencies:
  - name: common
    version: "0.1.10"
    repository: "file://../common"
