apiVersion: v2
name: event
description: Helm chart for the Clan Europe event management Discord bot
type: application
version: 0.1.8
appVersion: "main"
dependencies:
  - name: common
    version: "0.1.8"
    repository: "file://../common"
